### ISSUE TITLE
No scheduling

### ISSUE THREAD

**Issue by plundra** [gylle/sms900#3]
I'm planning to invest heavily in this project but I need the ability to schedule stuff.
Please fix or I will take my business elsewhere. Don't miss out on this opportunity of mass exposure.

**Comment by dhedberg** [comment]
Dear plundra,

Thank you for your very generous offer. Please be assured that we will prioritize this ticket with all haste.

Do not hesitate to reach out if you were to have any further questions, comments or demands.

**Comment by dhedberg** [comment]
Implemented in.. some recent commit.
